### ISSUE TITLE
premine

### ISSUE THREAD

**Issue by Projek-Kripto** [FndNur1Labs/CryptonoteEvo#120]
how to mine the genesis block reward? mining not start at height 0

**Comment by FndNur1Labs** [comment]
You need read doc. Premine works if many miner to mine. Calculate by
percentage coin supply.

**Comment by Refa20** [comment]
you must sync both read #118

**Comment by FndNur1Labs** [comment]
Half coin supply.

**Comment by FndNur1Labs** [comment]
Wait percentage sorry. My head numb
