### ISSUE TITLE
is this repo fixe the key image bug?

### ISSUE THREAD

**Issue by Goldeneum** [FndNur1Labs/CryptonoteEvo#121]
hey,
i cant see the bytecoin bug fixing here (look at: https://github.com/amjuarez/bytecoin/commit/abca08734ce2518257fb8beb3b48431e46e59c8e#commitcomment-22222054)
or, do you have another way to fix?

**Comment by FndNur1Labs** [comment]
what kind bug?private key export?. i will did but not much since forknote
found it. and we put here. now we try to generate simple code. and follow
up new bytecoin codes. they not much have premine since that. i need time
to configure v2 of Ruby[codename] version.

**Comment by FndNur1Labs** [comment]
fixed on lasy ruby v1

**Comment by Goldeneum** [comment]
the bug discovered about a year ago by monero devs, and fixed by bytecoin about a month after discovered..
but the old cryptonotefundation code is not batched i think, so your code osnt batched too (if its forked directly from the originak code).. !
take a look at : https://getmonero.org/2017/05/17/disclosure-of-a-major-bug-in-cryptonote-based-currencies.html

**Comment by FndNur1Labs** [comment]
Fork from bytecoin. Not from original.

**Comment by FndNur1Labs** [comment]
Fixed On V2[and atm this one fixed already] because old cryptonote many bug

Close cas.
